# Generated by Django 3.2.7 on 2021-10-01 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatinonTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_tag', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeopleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_sum', models.FloatField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('operation_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.operatinontag')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.operationtype')),
                ('people_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.peoplename')),
            ],
        ),
    ]
