# Generated by Django 3.2.7 on 2021-10-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperatinonTag',
            new_name='OperationTag',
        ),
    ]
