# Generated by Django 3.2.7 on 2021-10-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_operation_operation_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeopleName',
            new_name='People',
        ),
        migrations.RenameField(
            model_name='operationtag',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='operationtype',
            old_name='type_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='operationtag',
            name='type_id',
        ),
    ]
